[build]
  publish = "."
  functions = "netlify/functions"

# SPA fallback (les fichiers réels comme /merci.html restent prioritaires)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Alias pratique : /merci --> /merci.html
[[redirects]]
  from = "/merci"
  to = "/merci.html"
  status = 200
